### ISSUE TITLE
consolidate the Login and Sign-up functionality into a single button

### ISSUE THREAD

**Issue by dandyogiugo** [custodianinvestmentplc/trustees#3]
Currently, the website has two buttons - one for login and another for sign-up. We need to merge both functionalities - such that we create a single button - Login. This Login button will be placed on the top right hand corner of the site.

**Comment by RetroDj** [comment]
Approach
- First, sourced for best approach.
- Got resources required.

Implementation
- Create a new controller
- Create a new view
